# Generated by Django 4.1 on 2022-09-06 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='issueDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='issuedTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='models.member'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='returnDate',
            field=models.DateField(null=True),
        ),
    ]
