# Generated by Django 4.1 on 2022-09-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_copy_issuedate_alter_copy_issuedto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('borrower', models.ForeignKey(on_delete=models.SET('Deleted User'), to='models.member')),
                ('copy', models.ForeignKey(on_delete=models.SET('Delted Copy'), to='models.copy')),
            ],
        ),
    ]
