# Generated by Django 4.1 on 2022-09-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_remove_borrowhistory_returndate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnDate', models.DateField()),
                ('copy', models.ForeignKey(on_delete=models.SET('Deleted Copy'), to='models.copy')),
                ('member', models.ForeignKey(on_delete=models.SET('Deleted User'), to='models.member')),
            ],
        ),
    ]
