# Generated by Django 4.1 on 2022-09-11 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_verifyreturns'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fines',
            new_name='FinesHistory',
        ),
        migrations.CreateModel(
            name='PendingFines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.copy')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='models.member')),
            ],
        ),
        migrations.CreateModel(
            name='FineApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.pendingfines')),
            ],
        ),
    ]
