# Generated by Django 4.1 on 2022-09-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_rename_fines_fineshistory_pendingfines_fineapproval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowhistory',
            old_name='dueDate',
            new_name='returnDate',
        ),
    ]
