# Generated by Django 4.1 on 2022-09-11 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_rename_duedate_borrowhistory_returndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fineshistory',
            name='dueDate',
            field=models.DateField(default=datetime.date(2022, 9, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingfines',
            name='returnDate',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FineApproval',
        ),
    ]
